# Generated by Django 5.2.18 on 2026-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
